import streamlit as st
from PIL import Image
from diffusers import StableDiffusionPipeline
import torch

# Load Stable Diffusion model
@st.cache_resource
def load_model():
    model = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
    model.to("cuda" if torch.cuda.is_available() else "cpu")
    return model

st.title("DreamHome AI 🏡")
st.markdown("Generate home exteriors or interiors from text prompts using Stable Diffusion.")

prompt = st.text_input("Enter a prompt (e.g., 'Modern 2BHK floor plan')")

if prompt:
    with st.spinner("Generating image..."):
        model = load_model()
        image = model(prompt).images[0]
        st.image(image, caption="Generated by DreamHome AI", use_column_width=True)
